CREATE TABLE disability (
  id_disability INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL UNIQUE,
  pictogram VARCHAR(150) NOT NULL
);

CREATE TABLE company (
  id_company INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL,
  logo VARCHAR(400) NOT NULL
);

CREATE TABLE user (
  id_user INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  id_disability_fk INT NOT NULL,
  FOREIGN KEY (id_disability_fk) REFERENCES disability(id_disability)
);

CREATE TABLE account (
  id_account INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(100),
  password VARCHAR(250),
  assignement VARCHAR(100) NOT NULL,
  id_user_fk INT NOT NULL,
  id_company_fk INT NOT NULL,
  FOREIGN KEY (id_user_fk) REFERENCES user(id_user),
  FOREIGN KEY (id_company_fk) REFERENCES company(id_company)
);

CREATE TABLE sector (
  id_sector INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE offer (
  id_offer INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  date DATE NOT NULL,
  contract VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  location VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  id_sector_fk INT NOT NULL,
  FOREIGN KEY (id_sector_fk) REFERENCES sector(id_sector)
);

CREATE TABLE offer_disability (
  id_offer_fk INT NOT NULL,
  id_disability_fk INT NOT NULL,
  FOREIGN KEY (id_offer_fk) REFERENCES offer(id_offer),
  FOREIGN KEY (id_disability_fk) REFERENCES disability(id_disability)
);


CREATE TABLE operation (
  id_operation INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  date DATE NOT NULL,
  kind VARCHAR(100) NOT NULL,
  id_account_fk INT NOT NULL,
  id_offer_fk INT NOT NULL,
  FOREIGN KEY (id_account_fk) REFERENCES account(id_account),
  FOREIGN KEY (id_offer_fk) REFERENCES offer(id_offer)
);

INSERT INTO disability (name, pictogram) VALUES
('Handicap Moteur', '/assets/images/icons/disabled.svg'),
('Handicap Visuel', '/assets/images/icons/deafness.svg'),
('Handicap Auditif', '/assets/images/icons/unseen.svg'),
('Handicap Psychique', '/assets/images/icons/creative.svg'),
('Déficience Intellectuelle', '/assets/images/icons/brain.svg'),
('Maladies Invalidantes', '/assets/images/icons/health.svg');

INSERT INTO company (name, logo) VALUES
('CITEO', 'https://bo.citeo.com/sites/default/files/2020-11/Logo-Citeo.png'),
('MUTUALITE FRANCAISE AISNE NORD PAS DE CA', 'https://upload.wikimedia.org/wikipedia/fr/2/2d/Mutualite-fran%C3%A7aise.png'),
('Pôle Déficiences Visuelles', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi16TGn_VVEN3u8BC6pnhQGhQgcf-fWRXh1A&sg'),
('HOLDING LOUISE', 'https://www.pagesjaunes.fr/media/agc/57/93/31/00/00/4e/00/cb/da/0e/659d57933100004e00cbda0e/659d57933100004318cbda10.jpg'),
('ASS DEPART PUPILLES ENSEIGNEMENT PUBLIC', 'https://lucid.communiti.corsica/img/back/back-ass-depart-pupilles-enseig-publique-corse-du-sud.jpg'),
('CAHC', 'https://upload.wikimedia.org/wikipedia/fr/e/e1/Cahclogo.jpg'),
('DELEFORTRIE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_bPoKyQdff8HRsYHYHfSXuNAsOf_8gXdREw&s'),
('IEM LES CYCLADES', 'https://www.pagesjaunes.fr/media/agc/57/93/31/00/00/4e/00/cb/da/0e/659d57933100004e00cbda0e/659d57933100004318cbda10.jpg'),
('TALENTPEOPLE', 'https://static.observatoiredelafranchise.fr/images/logos/244/244/2448-logo_talentpeople.jpg'),
('LES ANGES GARDINS', 'https://www.cerdd.org/var/www/storage/images/mediatheque/cerdd/images/logos/logos-parcours-5/logo-les-anges-gardins/17219-1-fre-FR/logo-les-anges-gardins.jpg'),
('FIELD & SOLUTIONS', 'https://field-solutions.com/wp-content/uploads/2022/05/cropped-Logo-test.png'),
('ADAR SAMBRE AVESNOIS', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsA3iStVfMadbJtbUYyjWUbWuaZNcOqOjamg&s'),
('IZIMOME', 'https://media.licdn.com/dms/image/D4E22AQHt_gsheLltbA/feedshare-shrink_800/0/1709136498355?e=2147483647&v=beta&t=caxLCROd7F1HasG2Yc-S7jAhyYW62E4PUEDr2Fi_CWQ'),
('SCOP INSTEP', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT4AGWtWHm-1-92pGyGY25CwlOo327cbq-qxja6rcbakBgnMj_er3gWv8-rC3liEP7Vbo&usqp=CAU'),
('SIEGE PAPILLONS BLANCS ROUBAIX TOURCOING', 'https://www.papillonsblancs-rxtg.org/wp-content/uploads/2024/01/Papillons_unapei_quadri-png.png'),
('ADMIRAL INTERMEDIARY SERVICES SA', 'https://cdn.litige.fr/images/firms/2537/original/original.png?1676634096'),
('EVN', 'https://logowik.com/content/uploads/images/evn-ag7116.logowik.com.webp'),
('BOULANGERIE LOUISE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOiaCDZKlVIUOvgQrsHZNp00UawsN-hO2I2g&s'),
('O2', 'https://www.mayenne-communaute.net/wp-content/uploads/2021/05/O2.png'),
('GROUPE ALIAME', 'https://static.wixstatic.com/media/b01159_9b229153ca9c4f7298551c500f2a5310~mv2.jpg/v1/fill/w_400,h_400,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Groupe%20ALIAME_edited.jpg'),
('INSTITUT ECONOMIE SCIENTIFIQUE GESTION', 'https://pbs.twimg.com/profile_images/1310555745713258499/RsAHobX7_400x400.jpg'),
('LA VIE ACTIVE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaa9BLYWQb__4nh5tg-aiQW8p9uBCEu2B1jw&s'),
('BRAXES', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGuEMmeAeUPR3bxCQm6rJdbaba_SunitCorQ&s'),
('C.B.L', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4dZOLMLRZdv4_uKrxIu17CaQdRI9hAAMuyQ&s'),
('ACTION EDUCATIVE ET SOCIALE', 'https://www.aaedk.org/wp-content/uploads/2018/02/cropped-Logo198x100-1.png'),
('CCAS', 'https://couternon.fr/static/eb253ab74d462a43b939322ccbd1203d/bandeau-ccas.jpg'),
('AUXILIADOM', 'https://www.auxiliadom.com/wp-content/uploads/2023/04/logo_auxiliadom_ok.png'),
('SERVICE SOCIAL DU TRAVAIL', 'https://socialinter.fr/wp-content/uploads/Service-Social-du-Travail-Assistante-Sociale-et-Psychologue.jpg');


INSERT INTO user (firstname, lastname, id_disability_fk) VALUES
('Jean', 'Dupont', 1),
('Marie', 'Curie', 2),
('Pierre', 'Martin', 3),
('Sophie', 'Leroy', 4),
('Luc', 'Bernard', 5),
('Claire', 'Moreau', 6),
('Bernard', 'Marie', 5),
('Marie', 'Bizel', 4),
('Pierre', 'Forte', 2),
('Audrey', 'Morez', 1),
('Franck', 'Pelot', 1),
('Isabelle', 'Delfosse',2);

INSERT INTO sector (name) VALUES
('Commerce'),
('Vente'),
('Hôtellerie'),
('Restauration'),
('Tourisme'),
('Informatique'),
('Télécoms'),
('Tech'),
('Banque'),
('Assurance'),
('Finance'),
('Formation'),
('Recrutement'),
('Communication'),
('Marketing'),
('Distribution'),
('Grande consommation'),
('Direction'),
('useristration'),
('Santé'),
('Social'),
('Culture'),
('Média'),
('Divertissement'),
('Ingénierie'),
('BTP'),
('Urbanisme'),
('Autre fonction');

INSERT INTO account (email, password, assignement, id_user_fk, id_company_fk) VALUES
('john.doe@example.com', 'securepassword123', 'user', 1, 1),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 2),
('john.doe@example.com', 'securepassword123', 'user', 3, 3),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 4),
('john.doe@example.com', 'securepassword123', 'user', 1, 5),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 6),
('john.doe@example.com', 'securepassword123', 'user', 1, 7),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 8),
('john.doe@example.com', 'securepassword123', 'user', 4, 9),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 10),
('john.doe@example.com', 'securepassword123', 'user', 1, 11),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 12),
('john.doe@example.com', 'securepassword123', 'user', 5, 13),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 14),
('john.doe@example.com', 'securepassword123', 'user', 6, 15),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 16),
('john.doe@example.com', 'securepassword123', 'user', 7, 17),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 18),
('john.doe@example.com', 'securepassword123', 'user', 1, 19),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 20),
('john.doe@example.com', 'securepassword123', 'user', 8, 21),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 22),
('john.doe@example.com', 'securepassword123', 'user', 9, 23),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 24),
('john.doe@example.com', 'securepassword123', 'user', 10, 25),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 2, 26),
('john.doe@example.com', 'securepassword123', 'user', 11, 27),
('jane.smith@example.com', 'anothersecurepassword456', 'user', 12, 28);


INSERT INTO offer (date, contract, title, location, content, id_sector_fk) VALUES
('2024-06-15', 'CDD - Temps plein', 'Médiateur chantier (H/F)', 'Roubaix, 59', 'Citéo accompagne depuis 25 ans les entreprises, les collectivités et les collectifs de citoyens vers la conduite du changement, majoritairement en...', 26),
('2024-06-15', 'CDI - Temps plein', 'Préparateur en pharmacie HAD (H/F) DOUAI (H/F)', 'Douai, 59', 'Intégrer notre structure, c\'est rejoindre près de 800 professionnels et une vingtaine d\'élus bénévoles qui agissent au quotidien pour permettre l\'accès à des soins de...', 20),
('2024-06-15', 'CDD - Temps partiel', 'Secrétaire médical / médicale (H/F)', 'LOOS, 59', 'Le Pôle Déficiences Visuelles a pour mission d\'accompagner des jeunes en situation de handicap visuel (avec ou sans handicap associé) ainsi que leur famille...', 20),
('2024-06-15', 'CDD - Temps plein', 'Apprenti(e) Responsable Adjoint de Magasin - Longueau (H/F)', 'LONGUEAU, 80', 'Toi, tu veux te lever avec plaisir le matin pour aller au travail ? Fonce chez nous et prends soin de ton avenir, avec une alternance en tant que Responsable Adjoint de Magasin H/F...', 16),
('2024-06-15', 'CDI - Temps partiel', 'Agent de Service (H/F)', 'CAMPAGNE LES HESDIN, 62', 'Rejoignez l\'association départementale des Pupilles de d\'enseignement public du Nord-Pas-de-Calais. Vous aimez les projets humanitaires et la solidarité est au cœur de vos engagements ?', 21),
('2024-06-15', 'CDD - Temps plein', 'Ripeur collectes OM -Tri (H/F)', 'HENIN BEAUMONT, 62', 'Au sein d\'une équipe de trois personnes et sous la responsabilité du chauffeur de la benne, le ripeur assure la collecte des déchets ménagers dans le respect du règlement intérieur et du règlement de...', 27),
('2024-06-15', 'CDI - Temps plein', 'Chargé de développement RH (H/F)', 'ERQUINGHEM LYS, 59', 'Ayant la volonté d\'accompagner au plus près nos 43 collaborateurs au quotidien, dans un esprit humain, fédérateur et motivant, nous créons un poste de «Chargé(e) de développement des Ressources...', 13),
('2024-06-15', 'CDD - Temps plein', 'AES/AMP (H/F)', 'LEFOREST, 62', 'Sous la responsabilité de la Direction et dans le cadre des orientations du projet d\'établissement, vous contribuerez à l\'accompagnement des usagers au travers des missions suivantes : - Accompagner...', 21),
('2024-06-15', 'CDI - Temps plein', 'Responsable d\'agence de travail temporaire (H/F)', 'Chambly, 60', 'Nous recherchons pour notre agence Leader Intérim à Chambly (60) un ou une Responsable d\'Agence H/F. Sous la responsabilité du Directeur de secteur, vous gérez votre agence en toute autonomie et...', 13),
('2024-06-15', 'CDI - Temps plein', 'Encadrant.e Technique Maraîchage bio (H/F)', 'Loos-en-Gohelle, 62', 'L\'association Les Anges Gardins est une association loi 1901 d\'éducation populaire qui œuvre pour l\'insertion, l\'éducation permanente, le développement de nouvelles pratiques sociales et d\'activités...', 19),
('2024-06-15', 'CDD - Temps partiel', 'Enquêteur Terrain - Visite en boutique (H/F)', 'Somme, 80', 'Vous avez un sens affûté pour les détails et un sens aigu de l\'observation ? Nous avons l\'opportunité parfaite pour vous ! Qui sommes-nous ? Field & Solutions, entité du Topo Marketing Group, est...', 28),
('2024-06-15', 'CDD - Temps partiel', 'Assistant(e) parentale (H/F)', 'Maubeuge, 59', 'Fondée en 1979, sur le principe d\'un statut associatif sans but lucratif, l\'ADAR est orienté principalement vers l\'aide, le soin et l\'accompagnement à domicile de proximité. Rayonnant sur le pays...', 21),
('2024-06-15', 'CDI - Temps plein', 'Chargé(e) de mission RSE en alternance (H/F)', 'LESQUIN, 59', 'Le Groupe NAT s\'impose comme acteur leader d\'une offre globale et cohérente de solutions autour de réseaux sensibles comme non-sensibles. Il réunit 3 services, répondant tous à la Réforme...', 19),
('2024-06-15', 'CDD - Temps partiel', 'Enquêteur Terrain - Visite en Concession Automobile (H/F)', 'Aisne, 02', 'Vous avez un sens affûté pour les détails et un sens aigu de l\'observation ? Nous avons l\'opportunité parfaite pour vous ! Qui sommes-nous ? Field & Solutions, entité du Topo Marketing Group, est...', 28),
('2024-06-15', 'CDI - Temps partiel', 'Garde d\'enfant à domicile (H/F)', 'MAROEUIL, 62', 'Izimôme recrute pour une famille sur le secteur de Maroeuil. Vous souhaitez un emploi avec les enfants dans une agence chaleureuse et conviviale et vous avez de l\'expérience et/ou diplômé dans la...', 21),
('2024-06-15', 'CDD - Temps plein', 'Formatrice / Formateur pour adultes dans le sanitaire et social (H/F)', 'LILLE, 59', 'Faire acquérir des savoirs, savoir-faire, savoir-être inscrits dans une progression pédagogique au moyen de techniques éducatives appropriées, en s\'adaptant en permanence au public, en appréciant ses...', 12),
('2024-06-15', 'CDD - Temps plein', 'Moniteur-trice d\'atelier en Espaces Verts en alternance (H/F)', 'Linselles, 59', 'Vous participerez à l\'encadrement et l\'accompagnement d\'une équipe de travailleurs en situation de handicap sur des chantiers d\'espaces verts, principalement en entreprises...', 12),
('2024-06-15', 'CDI - Temps plein', 'Conseiller commercial / Conseillère commerciale en assurances (H/F)', 'MARCQ EN BAROEUL, 59', 'Vous aimez le challenge? Les objectifs ne vous font pas peur, bien au contraire, ils vous animent ? Ce poste est fait pour vous ! Votre rôle : Satisfaire nos clients et les rendre heureux ! Parce...', 1),
('2024-06-15', 'CDI - Temps plein', 'BOULANGER LOMME (H/F)', 'LILLE, 59', 'Véritable artisan, nous recherchons des professionnels avec un sens commercial développé et aimant le goût du travail bien fait. Nous cherchons un/une boulanger. Votre mission principale consistera à...', 4),
('2024-06-15', 'CDI - Temps partiel', 'Gouvernant(e) d\'enfant H/F Temps partiel sur Nieppe', 'Chapelle-d\'Armentières, 59', '**Polyvalent**, vous souhaitez participer pleinement au bien-être d\'une famille en assurant des temps de **garde des enfants à leur domicile les soirs après l\'école ou le mercredi** (activités...', 21),
('2024-06-15', 'CDI - Temps partiel', 'Garde d\'enfants H/F Temps partiel sur Quesnoy/Deule', 'Chapelle-d\'Armentières, 59', '**Polyvalent**, vous souhaitez participer pleinement au bien-être d\'une famille composée de **deux enfants de 5 ans et 1 an** qui habitent **Quesnoy/Deûle** en assurant à la fois des temps...', 21),
('2024-06-15', 'CDD - Temps plein', 'Aide soignant CDD remplacement H/F (H/F)', 'ST OMER, 62', 'Intégrer notre structure d\'hospitalisation à domicile, c\'est rejoindre des équipes qui agissent au quotidien pour permettre l\'accès à des soins de qualité au plus grand nombre. Notre objectif commun...', 20),
('2024-06-23', 'CDI - Temps plein', 'Responsable hygiène et approvisionnement (H/F)', 'WALINCOURT SELVIGNY, 59', 'SASU Tradinea est un service de restauration collective de proximité, dont les priorités sont la qualité des préparations, l\'approvisionnement local et un recrutement de proximité. Aujourd\'hui notre...', 4),
('2024-06-23', 'CDD - Temps plein', 'Apprenti(e) connecté(e) Boulanger (titre visé : CAP) (H/F)', 'Orchies, 59', 'Toi, tu veux te lever avec plaisir le matin pour aller au travail? Fonce chez nous et prends soin de ton avenir, avec une alternance en tant que Boulanger(e), pour Boulangerie Louise...', 4),
('2024-06-23', 'CDD - Temps plein', 'APPRENTI BOULANGER COMPIEGNE (H/F)', 'Compiègne, 60', 'Toi, tu veux te lever avec plaisir le matin pour aller au travail? Fonce chez nous et prends soin de ton avenir, avec une alternance en tant que Boulanger(e), pour Boulangerie Louise...', 4),
('2024-06-23', 'CDI - Temps plein', 'Appariteur des Services Généraux (H/F)', 'LILLE, 59', 'L\'IÉSEG recrute pour son Département Services Généraux sur le campus de Lille, un(e) Appariteur (H/F) des Services Généraux. Vos missions : Au sein de la Direction des Services Généraux, vous aurez...', 19),
('2024-06-23', 'CDI - Temps plein', 'Éducateur Spécialisé (H/F)', 'CAMPAGNE LES HESDIN, 62', 'L\'association PEP62 recrute pour un de ses établissements : La MECS de Campagne-les-Hesdin. Un Éducateur Spécialisé H/F. Dans le cadre d\'une création de poste, un CDI à temps complet. Vos missions...', 21),
('2024-06-23', 'CDD - Temps plein', 'Chauffeur ripeur polyvalent OM -Tri (H/F)', 'HENIN BEAUMONT, 62', 'Le chauffeur polyvalent assure la collecte des ordures ménagères résiduelles et des déchets recyclables dans le respect du règlement intérieur et du règlement de collecte. En fonction de la nécessité...', 27),
('2024-06-23', 'CDI - Temps plein', 'Agent / Agente de maintenance des bâtiments (H/F)', 'ST LAURENT BLANGY, 62', 'Méthodique et dynamique, vous savez faire preuve d\'autonomie dans votre travail. Vous êtes un vrai couteau suisse et vous savez prendre en charge les travaux de plomberie, carrelage, peinture...',28 ),
('2024-06-23', 'CDI - Temps partiel', 'Assistant / Assistante de vie (H/F)', 'HENIN BEAUMONT, 62', 'Vous intervenez auprès : Des familles Des personnes en situation de handicap Des personnes âgées. Conditions d\'exercice et avantages : Travail 1 week-end sur 2. Adaptation des plannings selon vos...', 21),
('2024-06-23', 'CDI - Temps plein', 'Assistant Marketing digital et communication f/h', 'LILLE, 59', 'Nous recherchons un(e) assistant(e) Marketing et Communication f/h pour participer activement à la stratégie et au développement de la communication de l\'entreprise. Votre mission : Gérer la...', 14),
('2024-06-23', 'CDD - Temps partiel', 'Auxiliaire de Vie Sociale -AVS- (H/F)', 'Maubeuge, 59', 'Poste à pourvoir sur le canton de Maubeuge et les communes environnantes. Ce poste nécessite d\'effectuer des déplacements quotidiens à domicile; participation aux frais kilométriques prévue. Vous...', 21),
('2024-06-23', 'CDD - Temps partiel', 'Formatrice/Formateur titulaire IDE (H/F)', 'LILLE, 59', 'Faire acquérir des savoirs, savoir-faire, savoir-être inscrits dans une progression pédagogique au moyen de techniques éducatives appropriées, en s\'adaptant en permanence au public, en appréciant ses...', 12),
('2024-06-23', 'CDD - Temps plein', 'Community manager en apprentissage (H/F)', 'NOYELLES GODAULT, 62', 'Nous un community manager en apprentissage pour partager l\'aventure Chez Madeleine avec nous! Ton rôle sera d\'animer les pages Facebook, Insta, Tiktok, Google et Linkedin avec publications, photos...', 14),
('2024-06-23', 'CDI - Temps plein', 'Assistant ménager H/F 35h Houplines + 10km', 'Chapelle-d\'Armentières, 59', 'Vous n\'avez pas d\'expérience et alors? Vous êtes un(e) véritable fé(e) du logis, un(e) as du ménage et de l\'entretien du domicile ? Venez avec votre engagement, votre volonté d\'offrir un service de...', 21),
('2024-06-23', 'CDI - Temps partiel', 'Assistant ménager H/F Temps partiel Quesnoy/Deule + 10km', 'Chapelle-d\'Armentières, 59', 'Vous n\'avez pas d\'expérience et alors? Vous êtes un(e) véritable fé(e) du logis, un(e) as du ménage et de l\'entretien du domicile ? Venez avec votre engagement, votre volonté d\'offrir un service de...', 21),
('2024-06-23', 'CDI - Temps partiel', 'Assistant ménager H/F Temps partiel La Chapelle-d\'Armentières + 10km', 'Chapelle-d\'Armentières, 59', 'Vous n\'avez pas d\'expérience et alors? Vous êtes un(e) véritable fé(e) du logis, un(e) as du ménage et de l\'entretien du domicile ? Venez avec votre engagement, votre volonté d\'offrir un service de...', 21),
('2024-06-23', 'CDI - Temps plein', 'IDECO CDI DOUAI (H/F)', 'Douai, 59', 'Au sein de votre établissement de rattachement, vous êtes un infirmier coordonnateur (IDEC), et vous avez pour mission principales de : Assurer les missions de liaison dans les établissements de...', 20),
('2024-06-23', 'CDD - Temps plein', 'Apprenti(e) Boulanger Libercourt (H/F)', 'Libercourt, 62', 'Fonce chez nous et prends soin de ton avenir, avec une alternance en tant que Boulanger(e), pour Boulangerie Louise Libercourt. Comment ? Avec une formule « 2 en 1 » toute simple : intégrer une...', 4),
('2024-06-23', 'CDI - Temps partiel', 'Aide-soignant / Aide-soignante (H/F)', 'COUDEKERQUE BRANCHE, 59', 'DESCRIPTION DU SERVICE ET MISSIONS DU POSTE À POURVOIR Les Lits Halte Soins Santé constituent une mobilité de prise en charge globale articulant fortement une dimension sociale et une dimension de...', 20),
('2024-06-23', 'CDD - Temps plein', 'Aide-soignant(e) en gériatrie en SSIAD  - Diplômé (H/F)', 'LOOS, 59', 'Au sein du SSIAD, vous accompagnez des personnes âgées  à domicile -aide au coucher -aide à la toilette et à l\'habillage -contrôle de la sécurité Vous faites preuve d\'écoute et vous aidez à la...', 20),
('2024-06-23', 'CDI - Temps plein', 'Conducteur routier régional / Conductrice routière régional (H/F)', 'Dourges, 62', 'Spécialisé dans la sous-traitance, nous recherchons un conducteur Permis EC, pour une tournée de distribution et ramasse au départ de notre client basé à Dourges Véhicule Semi Remorque attitré,...', 28),
('2024-06-23', 'CDI - Temps plein', 'CONDUCTEUR/(TRICE) DE TRAVAUX - Aménagement Paysager (H/F)', 'ERQUINGHEM LYS, 59', 'Points clés de notre environnement de travail : - Ambiance collective - Opportunités d\'évolution - Environnement dynamique Le/la conducteur/conductrice de travaux est responsable de la supervision...', 21),
('2024-06-23', 'CDD - Temps partiel', 'Assistant(e) de Vie aux Familles (H/F)', 'Maubeuge, 59', 'Fondée en 1979, sur le principe d\'un statut associatif sans but lucratif, l\'ADAR est orienté principalement vers l\'aide, le soin et l\'accompagnement à domicile de proximité. Rayonnant sur le pays...', 21),
('2024-06-23', 'CDI - Temps plein', 'Psychologue clinicien / clinicienne (H/F)', 'CAMBRAI, 59', 'Au sein d\'une association spécialisée dans l\'accompagnement des femmes victimes de violences, vous interviendrez  en soutien aux femmes victimes de violences sexistes et sexuelles. Vous agissez dans...', 20),
('2024-06-23', 'CDI - Temps partiel', 'Infirmier / Infirmière de santé au travail (H/F)', 'MAUBEUGE, 59', 'Dans le cadre de notre développement dans le secteur de la Métropole Lilloise, nous recrutons un(e) infirmier(e) de santé au travail. Vos principales missions : Suivi de Santé au Travail : o...', 20),
('2024-06-23', 'CDI - Temps plein', 'Comptable fournisseurs (H/F)', 'LILLE, 59', 'L\'IÉSEG recrute pour sa Direction useristrative et Financière sur le campus de Lille un(e) Comptable fournisseurs Missions En étroite collaboration avec la comptable fournisseurs, vos missions...', 19),
('2024-06-23', 'CDI - Temps plein', 'Comptable (H/F)', 'ST LAURENT BLANGY, 62', 'Forte de ses 4300 employés et engagée autour de fortes valeurs humaines, La Vie Active, association reconnue d\'utilité publique est un acteur central de l\'économie sociale et solidaire, qui n\'a de...', 19),
('2024-06-23', 'CDD - Temps plein', 'Référent expert médico social (H/F)', 'VALENCIENNES, 59', 'La Maison Départementale des Personnes Handicapées du Nord recrute, en CDD, 1 infirmier(e), pour son site de Valenciennes (Pôle Valenciennes-Avesnes). Votre mission consistera à apporter votre...', 21);

INSERT INTO operation (date, kind, id_account_fk, id_offer_fk) VALUES
('2023-06-01', 'postuler', 1, 1),
('2023-06-01', 'postuler', 2, 2),
('2023-06-01', 'postuler', 3, 3),
('2023-06-01', 'postuler', 4, 4),
('2023-06-01', 'postuler', 5, 5),
('2023-06-01', 'postuler', 6, 6),
('2023-06-01', 'postuler', 7, 7),
('2023-06-01', 'postuler', 8, 8),
('2023-06-01', 'postuler', 9, 9),
('2023-06-01', 'postuler', 10, 10),
('2023-06-01', 'postuler', 11, 11),
('2023-06-01', 'postuler', 12, 12),
('2023-06-01', 'postuler', 13, 13),
('2023-06-01', 'postuler', 11, 14),
('2023-06-01', 'postuler', 13, 15),
('2023-06-01', 'postuler', 14, 16),
('2023-06-01', 'postuler', 15, 17),
('2023-06-01', 'postuler', 16, 18),
('2023-06-01', 'postuler', 18, 19),
('2023-06-01', 'postuler', 19, 20),
('2023-06-01', 'postuler', 19, 21),
('2023-06-01', 'postuler', 2, 22),
('2023-06-01', 'postuler', 10, 23),
('2023-06-01', 'postuler', 4, 24),
('2023-06-01', 'postuler', 4, 25),
('2023-06-01', 'postuler', 21, 26),
('2023-06-01', 'postuler', 5, 27),
('2023-06-01', 'postuler', 6, 28),
('2023-06-01', 'postuler', 22, 29),
('2023-06-01', 'postuler', 25, 30),
('2023-06-01', 'postuler', 23, 31),
('2023-06-01', 'postuler', 12, 32),
('2023-06-01', 'postuler', 14, 33),
('2023-06-01', 'postuler', 24, 34),
('2023-06-01', 'postuler', 19, 35),
('2023-06-01', 'postuler', 19, 36),
('2023-06-01', 'postuler', 19, 37),
('2023-06-01', 'postuler', 2, 38),
('2023-06-01', 'postuler', 4, 39),
('2023-06-01', 'postuler', 25, 40),
('2023-06-01', 'postuler', 26, 41),
('2023-06-01', 'postuler', 17, 42),
('2023-06-01', 'postuler', 7, 43),
('2023-06-01', 'postuler', 12, 44),
('2023-06-01', 'postuler', 5, 45),
('2023-06-01', 'postuler', 28, 46),
('2023-06-01', 'postuler', 21, 47),
('2023-06-01', 'postuler', 22, 48),
('2023-06-01', 'postuler', 27, 49);

INSERT INTO offer_disability (id_offer_fk, id_disability_fk) VALUES
(1, 1),
(1, 3),
(2, 2),
(2, 4),
(2, 5),
(3, 3),
(3, 5),
(4, 1),
(4, 4),
(5, 1),
(5, 4),
(5, 3),
(6, 4),
(6, 3),
(6, 1),
(7, 4),
(8, 5),
(8, 3),
(9, 5),
(9, 1),
(10, 4),
(11, 1),
(11, 6),
(12, 3),
(13, 1),
(14, 3),
(14, 2),
(15, 4),
(16, 5),
(17, 3),
(18, 5),
(19, 1),
(19, 4),
(20, 1),
(20, 4),
(20, 3),
(21, 1),
(22, 3),
(23, 2),
(24, 4),
(25, 5),
(26, 3),
(26, 5),
(27, 1),
(27, 4),
(28, 1),
(29, 4),
(30, 3),
(30, 1),
(31, 3),
(31, 2),
(32, 4),
(33, 5),
(33, 3),
(34, 5),
(35, 1),
(36, 4),
(37, 1),
(38, 4),
(38, 3),
(38, 1),
(39, 3),
(39, 2),
(40, 4),
(40, 5),
(41, 3),
(42, 5),
(43, 1),
(43, 4),
(44, 1),
(44, 4),
(45, 3),
(45, 5),
(46, 1),
(46, 4),
(47, 1),
(47, 4),
(47, 3),
(48, 1),
(48, 3),
(49, 2);
